name: flutter_popup
description: The flutter_popup package is a convenient tool that enables you to display a straightforward and customizable popup within your Flutter application. It offers a highlight feature that can be utilized to direct the user's attention to a specific area as needed.
version: 3.1.6
homepage: https://github.com/herowws/flutter_popup

environment:
  sdk: '>=2.17.0 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter
  
 
dev_dependencies:
  example:
    path: example
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

 