name: flutter_popup
description: beautiful popup for flutter
version: 3.1.3
homepage: https://github.com/herowws/flutter_popup

environment:
  sdk: '>=2.17.0 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter
  
 
dev_dependencies:
  example:
    path: example
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

 